project_id = "gjqbbgrfhijescaouqkx"

[functions.universal-bison-webhook]
verify_jwt = false

[functions.airtable-clients]
verify_jwt = false

[functions.airtable-email-accounts]
verify_jwt = false

[functions.airtable-campaigns]
verify_jwt = false

[functions.airtable-sending-volume]
verify_jwt = false

[functions.streetsmart-commercial-webhook]
verify_jwt = false

[functions.streetsmart-trucking-webhook]
verify_jwt = false

[functions.streetsmart-pc-webhook]
verify_jwt = false

[functions.schrauf-agency-webhook]
verify_jwt = false

[functions.jason-binyon-webhook]
verify_jwt = false

[functions.noah-sisson-webhook]
verify_jwt = false

[functions.john-leblanc-webhook]
verify_jwt = false

[functions.castle-agency-webhook]
verify_jwt = false

[functions.casanas-agency-webhook]
verify_jwt = false