project_id = "gjqbbgrfhijescaouqkx"

[functions.universal-bison-webhook]
verify_jwt = false

[functions.airtable-clients]
verify_jwt = false

[functions.airtable-email-accounts]
verify_jwt = false

[functions.airtable-campaigns]
verify_jwt = false

[functions.airtable-sending-volume]
verify_jwt = false

[functions.streetsmart-commercial-webhook]
verify_jwt = false

[functions.streetsmart-trucking-webhook]
verify_jwt = false

[functions.streetsmart-pc-webhook]
verify_jwt = false